Router.addRoutes [{
  route: 'home'
  path: '/'
  controller: "ExampleController"
  page:
    title: "jQuery DataTables"
    subtitle: "Sort, page, and filter millions of records reactively."
},{
  route: 'datasources'
  path: 'datasources'
  controller: "ExampleController"
  page:
    title: "Data Sources"
    subtitle: "DOM, Array, or Live Cursor."
  nav:
    priority: 1
    icon: 'icon-stack'
},{
  route: 'colVis'
  path: 'column-visibility'
  controller: "ExampleController"
  page:
    title: "Column Visibility"
    subtitle: "Show and hide columns on the fly."
  nav:
    priority: 2
    icon: 'icon-search'
},{
  route: 'colReorder'
  path: 'column-reorder'
  controller: "ExampleController"
  page:
    title: "Column Reorder"
    subtitle: "Put it wherever you want."
  nav:
    priority: 3
    icon: 'icon-search'
},{
  route: 'columnFilters'
  path: 'column-filters'
  controller: "ExampleController"
  page:
    title: "Column Filters"
    subtitle: "Drill Down and text search."
  nav:
    priority: 4
    icon: 'icon-search'
},{
  route: 'gitHub'
  path: "https://github.com/lumapictures/meteor-jquery-datatables"
  external: true
  page:
    title: "GitHub"
    subtitle: "Open Source Repo"
  nav:
    priority: 1000
    icon: 'icon-github'
},{
  route: 'reportBugs'
  path: "https://github.com/lumapictures/meteor-jquery-datatables/issues/new"
  external: true
  page:
    title: "Report Bugs"
    subtitle: "GitHub Issues"
},{
  route: 'source'
  path: "http://lumapictures.github.io/meteor-jquery-datatables/"
  external: true
  page:
    title: "Annotated Source"
    subtitle: "GitHub pages generated by Groc"
  nav:
    priority: 1001
    icon: 'icon-code'
},{
  route: 'build'
  path: "https://travis-ci.org/LumaPictures/meteor-jquery-datatables"
  external: true
  page:
    title: "Build Status"
    subtitle: "Continuous Integration by Travis CI"
  nav:
    priority: 1002
    icon: 'icon-cogs'
}]

Router.initialize()