Router.addRoutes [{
  route: 'home'
  path: '/'
  controller: "ExampleController"
  page:
    title: "Home"
    subtitle: "Sort, page, and filter millions of records reactively."
},{
  route: 'examples'
  path: 'examples'
  page:
    title: "Examples"
    subtitle: "Meteor usage examples."
  nav:
    priority: 1
    icon: 'icon-happy2'
    children: [{
      title: "Data Sources"
      route: "dataSources"
    },{
      title: "Blaze Templates"
      route: "blazeTemplates"
    },{
      title: "Nested Table"
      route: "nestedTable"
    },{
      title: "Reactive Query"
      route: "reactiveQuery"
    }]
},{
  route: 'dataSources'
  path: '/examples/data-sources'
  controller: "ExampleController"
  page:
    title: "Data Sources"
    subtitle: "DOM, Array, or Live Cursor."
 },{
  route: "blazeTemplates"
  path: "/examples/blaze-templates"
  controller: "ExampleController"
  page:
    title: "Blaze Templates"
    subtitle: "Reactive templates in table cells."
},{
  route: "reactiveQuery"
  path: "/examples/reactive-query"
  controller: "ExampleController"
  page:
    title: "Reactive Query"
    subtitle: "Rerender DataTable when the query changes."
},{
  route: "nestedTable"
  path: "/examples/nested-table"
  controller: "ExampleController"
  page:
    title: "Nested Tables"
    subtitle: "Yo Dawg, heard you like tables."
},{
  route: "extensions"
  path: "/extensions"
  page:
    title: "Extensions"
    subtitle: "jQuery DataTables extensions."
  nav:
    priority: 2
    icon: "icon-puzzle"
    children: [{
      route: "colVis"
      title: "Column Visibility"
    },{
      route: "colReorder"
      title: "Column Reorder"
    },{
      route: "colFilters"
      title: "Column Filters"
    }]
},{
  route: 'colVis'
  path: '/extensions/column-visibility'
  controller: "ExampleController"
  page:
    title: "Column Visibility"
    subtitle: "Show and hide columns on the fly."
},{
  route: 'colReorder'
  path: '/extensions/column-reorder'
  controller: "ExampleController"
  page:
    title: "Column Reorder"
    subtitle: "Put it wherever you want."
},{
  route: 'colFilters'
  path: '/extensions/column-filters'
  controller: "ExampleController"
  page:
    title: "Column Filters"
    subtitle: "Drill Down and text search."
},{
  route: 'resources'
  path: "https://datatables.net/"
  external: true
  page:
    title: "Official Resources"
    subtitle: "Official jQuery DataTables resources"
  nav:
    priority: 999
    icon: "icon-book"
},{
  route: 'gitHub'
  path: "https://github.com/lumapictures/meteor-jquery-datatables"
  external: true
  page:
    title: "GitHub"
    subtitle: "Open Source Repo"
  nav:
    priority: 1000
    icon: 'icon-github'
},{
  route: 'reportBugs'
  path: "https://github.com/lumapictures/meteor-jquery-datatables/issues/new"
  external: true
  page:
    title: "Report Bugs"
    subtitle: "GitHub Issues"
},{
  route: 'source'
  path: "http://lumapictures.github.io/meteor-jquery-datatables/"
  external: true
  page:
    title: "Annotated Source"
    subtitle: "GitHub pages generated by Groc"
  nav:
    priority: 1001
    icon: 'icon-code'
},{
  route: 'build'
  path: "https://travis-ci.org/LumaPictures/meteor-jquery-datatables"
  external: true
  page:
    title: "Build Status"
    subtitle: "Continuous Integration by Travis CI"
  nav:
    priority: 1002
    icon: 'icon-cogs'
}]

Router.initialize()